force-app/main/default/objects/Image__c/Image__c.object-meta.xml
<CustomObject>
    <description>here we are storing Url from Git , then we can used in CMP</description>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>where we are using in Community</description>
    <label>Display Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Image__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>kown the Source of Image</description>
    <label>Source</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Image__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>here we can store URL</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Inv_ImageController.cls
public with sharing class Inv_ImageController {
    
    @AuraEnabled(cacheable=true)
    public static List<Image__c> getImages(String Source, String Display_Name,String Variable) {
        // Query to get the images' URLs
        return [SELECT Id, Name,Display_Name__c, URL__c FROM Image__c 
                WHERE Source__c =: Source AND
                 Display_Name__c =: Display_Name AND 
                 Variable__c =: Variable
                 ];
    }


}