force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <description>here we can store Post Comments</description>
    <label>Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Comment_Id__c</fullName>
    <description>Here we can store Comment id</description>
    <displayFormat>CO-{000000}</displayFormat>
    <label>Comment Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Here we can store Post Comment.</description>
    <label>Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <description>Here we can store Post id</description>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <description>used this object to store user Posts</description>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>Here we  an store Content of Post</description>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Post__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Here we can store Title Value</description>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/inv_PostController.cls
public with sharing class inv_PostController {
    @AuraEnabled(cacheable=true)
    public static List<Post__c> getPosts() {
        // Fetch all posts along with related comments
        return [SELECT Id, Title__c, Content__c,
                    (SELECT Id, Content__c, CreatedById
                    FROM Comments__r)
            FROM Post__c ORDER BY Created_At__c DESC LIMIT 30];
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<Comment__c> getComments(String postId){
        return [SELECT Id,Comment_Id__c,Name,Content__c,
                Post__c FROM Comment__c WHERE Post__c =: postId LIMIT 30];
    }
    
    @AuraEnabled
    public static String updatePost(String postId,String content){
        Post__c ps = new Post__c();
        ps.Content__c = content;
        ps.Id = postId;
        update ps;
        return 'success';
    }
    @AuraEnabled
    public static String updateComment(String commentId,String content){
        Comment__c comm = new Comment__c();
        comm.Content__c = content;
        comm.Id = commentId;
        update comm;
        return 'success';
    }
}